name: 'Install PHP'
description: 'Install PHP and dependencies'

runs:
  using: composite
  steps:
    - name: Detect PHP version
      id: version
      shell: bash
      run: |
        echo "value=$(jq '"8.1|" + .require."php" | split("|") | map(select(. != "")) | last | sub("^[^\\d]+"; "")' -r -c composer.json)" >> $GITHUB_OUTPUT

    - name: Detect required PHP extensions
      id: extensions
      shell: bash
      run: |
        echo "value=$(jq '[."require", ."require-dev", ."suggest"] | add | to_entries | map(select(.key | match("ext-";"i"))) | map(.key | sub("ext-"; "")) | sort' -r -c composer.json)" >> $GITHUB_OUTPUT

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ steps.version.outputs.value}}
        extensions: ${{ join(fromJSON(steps.extensions.outputs.value)) }}
        coverage: none
        tools: cs2pr

    - name: Setup ENV
      shell: bash
      run: |
        cp .github/default.env .env

    - name: Install dependencies
      uses: ramsey/composer-install@v2

    - name: Setup problem matchers
      shell: bash
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
