SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `distributors` (
  `id`         CHAR(36)     NOT NULL,
  `name`       VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP    NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP    NULL      DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx__deleted_at` (`id` ASC, `deleted_at` ASC) VISIBLE);

ALTER TABLE `documents`
    ADD COLUMN `distributor_id` CHAR(36) NULL DEFAULT NULL AFTER `reseller_id`,
    ADD INDEX `fk_document_distributors1_idx` (`distributor_id` ASC) VISIBLE,
    ADD CONSTRAINT `fk_documents_distributors1`
        FOREIGN KEY (`distributor_id`)
        REFERENCES `distributors` (`id`)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
