SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS = 1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `users`
    ADD COLUMN `office_phone`   VARCHAR(255) NULL DEFAULT NULL AFTER `enabled`,
    ADD COLUMN `contact_email`  VARCHAR(255) NULL DEFAULT NULL AFTER `office_phone`,
    ADD COLUMN `title`          VARCHAR(7)   NULL DEFAULT NULL AFTER `contact_email`,
    ADD COLUMN `academic_title` VARCHAR(255) NULL DEFAULT NULL AFTER `title`,
    ADD COLUMN `mobile_phone`   VARCHAR(255) NULL DEFAULT NULL AFTER `academic_title`,
    ADD COLUMN `department`     VARCHAR(255) NULL DEFAULT NULL AFTER `mobile_phone`,
    ADD COLUMN `job_title`      VARCHAR(255) NULL DEFAULT NULL AFTER `department`,
    ADD COLUMN `company`        VARCHAR(255) NULL DEFAULT NULL AFTER `job_title`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
