SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 1;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 1;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `assets`
    ADD COLUMN `changed_at` TIMESTAMP NULL DEFAULT NULL AFTER `contacts_count`;

ALTER TABLE `customers`
    ADD COLUMN `changed_at` TIMESTAMP NULL DEFAULT NULL AFTER `contacts_count`;

ALTER TABLE `documents`
    ADD COLUMN `changed_at` TIMESTAMP NULL DEFAULT NULL AFTER `contacts_count`;

ALTER TABLE `resellers`
    ADD COLUMN `changed_at` TIMESTAMP NULL DEFAULT NULL AFTER `contacts_count`;

ALTER TABLE `distributors`
    ADD COLUMN `changed_at` TIMESTAMP NULL DEFAULT NULL AFTER `name`;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
