SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 1;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 1;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `documents`
    ADD COLUMN `assets_count`                       INT(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `language_id`,
    CHANGE COLUMN `number` `number`                 VARCHAR(64)      NOT NULL,
    CHANGE COLUMN `entries_count` `entries_count`   INT(11) UNSIGNED NOT NULL DEFAULT 0,
    CHANGE COLUMN `contacts_count` `contacts_count` INT(11) UNSIGNED NOT NULL DEFAULT 0;

UPDATE `documents` d
SET d.`assets_count` = (
    SELECT COUNT(DISTINCT e.`asset_id`)
    FROM `document_entries` e
    WHERE e.`document_id` = d.`id`
);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
