SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 1;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 1;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `customers`
    DROP FOREIGN KEY `fk_customers_types1`;

ALTER TABLE `resellers`
    DROP FOREIGN KEY `fk_resellers_types1`;

ALTER TABLE `customers`
    DROP COLUMN `type_id`,
    DROP INDEX `fk_customers_types1_idx`;

ALTER TABLE `resellers`
    DROP COLUMN `type_id`,
    DROP INDEX `fk_resellers_types1_idx`;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
