<?php declare(strict_types = 1);

use App\Services\Settings\Migrations\SettingsRename;

return new class() extends SettingsRename {
    /**
     * @inheritdoc
     */
    protected function getRenameMap(): array {
        return [
            'EP_DATA_LOADER_RESELLERS_UPDATER_ENABLED'    => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_ENABLED',
            'EP_DATA_LOADER_RESELLERS_UPDATER_CRON'       => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_CRON',
            'EP_DATA_LOADER_RESELLERS_UPDATER_QUEUE'      => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_QUEUE',
            'EP_DATA_LOADER_RESELLERS_UPDATER_TIMEOUT'    => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_TIMEOUT',
            'EP_DATA_LOADER_RESELLERS_UPDATER_TRIES'      => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_TRIES',
            'EP_DATA_LOADER_RESELLERS_UPDATER_CHUNK'      => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_CHUNK',
            'EP_DATA_LOADER_RESELLERS_UPDATER_EXPIRE'     => 'EP_DATA_LOADER_RESELLERS_SYNCHRONIZER_EXPIRE',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_ENABLED'    => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_ENABLED',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_CRON'       => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_CRON',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_QUEUE'      => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_QUEUE',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_TIMEOUT'    => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_TIMEOUT',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_TRIES'      => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_TRIES',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_CHUNK'      => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_CHUNK',
            'EP_DATA_LOADER_CUSTOMERS_UPDATER_EXPIRE'     => 'EP_DATA_LOADER_CUSTOMERS_SYNCHRONIZER_EXPIRE',
            'EP_DATA_LOADER_ASSETS_UPDATER_ENABLED'       => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_ENABLED',
            'EP_DATA_LOADER_ASSETS_UPDATER_CRON'          => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_CRON',
            'EP_DATA_LOADER_ASSETS_UPDATER_QUEUE'         => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_QUEUE',
            'EP_DATA_LOADER_ASSETS_UPDATER_TIMEOUT'       => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_TIMEOUT',
            'EP_DATA_LOADER_ASSETS_UPDATER_TRIES'         => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_TRIES',
            'EP_DATA_LOADER_ASSETS_UPDATER_CHUNK'         => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_CHUNK',
            'EP_DATA_LOADER_ASSETS_UPDATER_EXPIRE'        => 'EP_DATA_LOADER_ASSETS_SYNCHRONIZER_EXPIRE',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_ENABLED' => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_ENABLED',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_CRON'    => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_CRON',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_QUEUE'   => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_QUEUE',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_TIMEOUT' => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_TIMEOUT',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_TRIES'   => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_TRIES',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_CHUNK'   => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_CHUNK',
            'EP_DATA_LOADER_DISTRIBUTORS_UPDATER_EXPIRE'  => 'EP_DATA_LOADER_DISTRIBUTORS_SYNCHRONIZER_EXPIRE',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_ENABLED'    => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_ENABLED',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_CRON'       => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_CRON',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_QUEUE'      => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_QUEUE',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_TIMEOUT'    => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_TIMEOUT',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_TRIES'      => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_TRIES',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_CHUNK'      => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_CHUNK',
            'EP_DATA_LOADER_DOCUMENTS_UPDATER_EXPIRE'     => 'EP_DATA_LOADER_DOCUMENTS_SYNCHRONIZER_EXPIRE',
        ];
    }
};
