name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpcs:
    uses: ./.github/workflows/phpcs.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml

  phpunit:
    uses: ./.github/workflows/phpunit.yml

  graphql:
    uses: ./.github/workflows/graphql.yml
    needs:
      - phpunit
