name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: ./.github/workflows/settings.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpstan:
    uses: ./.github/workflows/phpstan.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpunit:
    uses: ./.github/workflows/phpunit.yml
    needs:
      - settings
      - phpstan
      - phpcs
    with:
      php-versions: ${{ needs.settings.outputs.php-versions }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  graphql:
    runs-on: ubuntu-latest
    needs:
      - phpunit
    steps:
      - name: Vars
        run: |
          JOB_PWD=tmp
          GRAPHQL_SCHEMA=app/GraphQL/ServiceTest~public.graphql
          GRAPHQL_CHANGES="${JOB_PWD}/GraphQLSchemaChanges.txt"
          GRAPHQL_PREVIOUS="${JOB_PWD}/previous"
          GRAPHQL_PREVIOUS_SCHEMA="${GRAPHQL_PREVIOUS}/${GRAPHQL_SCHEMA}"
          GRAPHQL_IS_PR="${{ github.event_name == 'pull_request' }}"
          GRAPHQL_IS_STRICT="${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, '!') }}"

          echo "GRAPHQL_SCHEMA=${GRAPHQL_SCHEMA}"  >> $GITHUB_ENV
          echo "GRAPHQL_CHANGES=${GRAPHQL_CHANGES}" >> $GITHUB_ENV
          echo "GRAPHQL_PREVIOUS=${GRAPHQL_PREVIOUS}" >> $GITHUB_ENV
          echo "GRAPHQL_PREVIOUS_SCHEMA=${GRAPHQL_PREVIOUS_SCHEMA}" >> $GITHUB_ENV
          echo "GRAPHQL_IS_PR=${GRAPHQL_IS_PR}" >> $GITHUB_ENV
          echo "GRAPHQL_IS_STRICT="${GRAPHQL_IS_STRICT}"" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Checkout previous
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: "${{ env.GRAPHQL_PREVIOUS }}"
          ref: "${{ env.GRAPHQL_IS_PR && github.event.pull_request.base.ref || '' }}"
      - name: Switch to previous
        run: |
          cd "${{ env.GRAPHQL_PREVIOUS }}"
          git checkout HEAD~1
      - name: Check
        if: hashFiles(env.GRAPHQL_PREVIOUS_SCHEMA)
        run: |
          if [ ! $(npx graphql-inspector diff "${{ env.GRAPHQL_PREVIOUS_SCHEMA }}" "${{ env.GRAPHQL_SCHEMA }}" > "${{ env.GRAPHQL_CHANGES }}") ] && [ "${{ env.GRAPHQL_PR_STRICT }}" = 'true' ]; then
            exit 1;
          fi
      - name: Summary
        if: always() && hashFiles(env.GRAPHQL_CHANGES)
        run: |
          cat "${{ env.GRAPHQL_CHANGES }}" >> $GITHUB_STEP_SUMMARY
