name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: ./.github/workflows/settings.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpstan:
    uses: ./.github/workflows/phpstan.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpunit:
    uses: ./.github/workflows/phpunit.yml
    needs:
      - settings
    with:
      php-versions: ${{ needs.settings.outputs.php-versions }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}
