name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: ./.github/workflows/settings.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpstan:
    uses: ./.github/workflows/phpstan.yml
    needs:
      - settings
    with:
      php-version: ${{ needs.settings.outputs.php-latest }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  phpunit:
    uses: ./.github/workflows/phpunit.yml
    needs:
      - settings
    with:
      php-versions: ${{ needs.settings.outputs.php-versions }}
      php-extensions: ${{ needs.settings.outputs.php-extensions }}

  graphql:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "${{ github.event.pull_request.base.ref }}:app/GraphQL/ServiceTest~public.graphql"
          annotations: false
          approve-label: "!"
          fail-on-breaking: ${{ github.event.pull_request.base.ref == 'dev' }}
