name: PHP Code Sniffer

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
      - name: Setup PHP
        uses: ./.github/actions/php
      - name: Execute
        run: |
          vendor/bin/phpcs --report=checkstyle | cs2pr
