name: PHP Code Sniffer

on:
  push:
    branches:
      - dev
  pull_request:
    branches-ignore:
      - main
      - staging
  workflow_dispatch:

jobs:
  settings:
    uses: .github/settings.yml

  phpcs:
    name: "Check"
    runs-on: ubuntu-latest
    needs:
      - settings
    steps:
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.settings.outputs.php-latest }}
          extensions: ${{ needs.settings.outputs.extensions }}
          tools: cs2pr
      - name: Setup App
        run: |
          cp .env.github .env
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Execute
        run: |
          vendor/bin/phpcs --report=checkstyle | cs2pr
