name: PHP Code Sniffer

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      php-extensions:
        description: "The JSON with required php extensions."
        required: true
        type: string

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ join(fromJSON(inputs.php-extensions)) }}
          coverage: none
          tools: cs2pr
      - name: Setup App
        run: |
          cp .github/default.env .env
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Execute
        run: |
          vendor/bin/phpcs --report=checkstyle | cs2pr
