name: PHP Stan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest

    services:
      # Redis is required because Larastan boots Laravel app while analyse. So
      # if no Redis installed it will fail with "Connection refused".
      #
      # https://github.com/nunomaduro/larastan/issues/1196
      # https://github.com/nunomaduro/larastan/issues/1072
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: ./.github/actions/checkout
      - name: Setup PHP
        uses: ./.github/actions/php
      - name: Execute
        run: |
          vendor/bin/phpstan analyse
