name: PHP Stan

env:
  PHP_VERSION: "8.0"

on:
  push:
    branches:
      - dev
  pull_request_target:
    branches:
      - dev
  workflow_dispatch:

jobs:
  settings:
    name: Collect settings
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.extensions.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Detect PHP extensions
        id: extensions
        run: |
          echo "::set-output name=value::$(jq '[.require, ."require-dev", .suggest] | add | to_entries | map(select(.key | match("ext-";"i"))) | map(.key | sub("ext-"; "")) | join(", ")' -r -c composer.json)"

  phpstan:
    name: "Analyze"
    runs-on: ubuntu-latest
    needs:
      - settings

    services:
      # Redis is required because Larastan boots Laravel app while analyse. So
      # if no Redis installed it will fail with "Connection refused".
      #
      # https://github.com/nunomaduro/larastan/issues/1196
      # https://github.com/nunomaduro/larastan/issues/1072
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ needs.settings.outputs.extensions }}
      - name: Setup App
        run: |
          cp .env.github .env
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Execute
        run: |
          vendor/bin/phpstan analyse
